BestGadget/app/models/buygadgets.js
BestGadget/public/js/buyGadget.js

table altered

---

BestGadget/app/routes.js
BestGadget/public/css/bestGadget.css
BestGadget/views/productDetails.handlebars

Product details page

---

BestGadget/app/models/buygadgets.js
BestGadget/app/models/proudct.js
BestGadget/app/routes.js
BestGadget/public/js/buyGadget.js
BestGadget/seed/product-seeder.js
BestGadget/views/home.handlebars
BestGadget/views/layouts/layout.handlebars

Loading products and iterating popular products dynamically on home page

Loading products and iterating popular products dynamically on home page

---

BestGadget/public/css/bestGadget.css
BestGadget/views/home.handlebars
BestGadget/views/productDetails.handlebars

minor fixes to the home page

---

BestGadget/app/routes.js
BestGadget/server.js

proper re directions for login and logout added

proper re directions for login and logout added

---

BestGadget/app/routes.js
BestGadget/public/css/bestGadget.css
BestGadget/public/js/buyGadget.js
BestGadget/views/categoryLanding.handlebars
BestGadget/views/home.handlebars
BestGadget/views/layouts/layout.handlebars

Product Landing page using handlebars

Product Landing page using handle bars

---

BestGadget/public/css/bestGadget.css
BestGadget/views/categoryLanding.handlebars

Resolved CSS issue affecting the sigin

Resolved CSS issue affecting the sigin

---

BestGadget/public/css/bestGadget.css
BestGadget/views/categoryLanding.handlebars
BestGadget/views/home.handlebars

product catalog page

---

BestGadget/app/models/ProductCart.js
BestGadget/app/routes.js
BestGadget/views/home.handlebars
BestGadget/views/layouts/layout.handlebars

traversing the data on click of Add Cart button

traversing the data on click of Add Cart button

---

BestGadget/public/css/bestGadget.css
BestGadget/views/cart.handlebars

changes to the cart page view

---

BestGadget/app/models/ProductCart.js
BestGadget/app/routes.js
BestGadget/public/css/bestGadget.css
BestGadget/views/cart.handlebars
BestGadget/views/layouts/layout.handlebars

Completed the functionality of add to cart

Completed the functionality of add to cart

---

BestGadget/app/models/proudct.js

changes to the productbuygadgets collection

changes to the productbuygadgets collection

---

BestGadget/app/routes.js
BestGadget/public/css/bestGadget.css
BestGadget/views/categoryLanding.handlebars
BestGadget/views/home.handlebars
BestGadget/views/layouts/layout.handlebars
BestGadget/views/productDetails.handlebars

nav bar ,pdp page and category page changes

nav bar ,pdp page and category page changes

---

BestGadget/public/css/bestGadget.css
BestGadget/views/categoryLanding.handlebars
BestGadget/views/productDetails.handlebars

category landing and pdp page changes

category landing and pdp page changes

---

BestGadget/app/routes.js

passport session rerouting

---

BestGadget/app/models/ProductCart.js
BestGadget/app/routes.js

Minor changes

---

BestGadget/views/cart.handlebars

pdp redirection added

---

BestGadget/public/js/checkoutPayment.js

checkout validation error resolved

checkout validation error resolved

---

BestGadget/views/cart.handlebars

Quantity range filed disabled

---

BestGadget/views/layouts/layout.handlebars

fav icon fix

---

BestGadget/public/css/bestGadget.css

breadcrumb changes

---

BestGadget/app/routes.js

route changes for checkout

---

BestGadget/app/routes.js
BestGadget/views/checkout.handlebars

Branch amish

---

BestGadget/views/layouts/layout.handlebars
BestGadget/views/login.handlebars
BestGadget/views/register.handlebars

static link configuration

---

BestGadget/app/routes.js
BestGadget/public/css/bestGadget.css
BestGadget/views/cancellation.handlebars
BestGadget/views/faq.handlebars
BestGadget/views/home.handlebars
BestGadget/views/login.handlebars
BestGadget/views/payments.handlebars
BestGadget/views/productDetails.handlebars
BestGadget/views/register.handlebars
BestGadget/views/security.handlebars
BestGadget/views/shipping.handlebars

overall changes

---

BestGadget/public/css/bestGadget.css
BestGadget/views/layouts/layout.handlebars

css minor changes

---

BestGadget/public/css/bestGadget.css

css changes

---

BestGadget/.gitignore

Changes to git ignore

---

BestGadget/views/contactus.handlebars

background color

---

BestGadget/.gitignore

added readme to git ignore

---

BestGadget/.gitignore

git ignore changes

---

README.md

read me added

---

README.md

changes to log out functionality

changes to log out functionality
